#include<stdio.h>

int main()
{
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("\nI D K\t");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    printf("KIIT UNIVERSITY");
    return 0;
}